# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestAnnu():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_annu(self):
        self.driver.get("https://trytestingthis.netlify.app/")
        self.driver.set_window_size(803, 816)
        self.driver.find_element(By.ID, "fname").click()
        self.driver.find_element(By.ID, "fname").send_keys("anu")
        self.driver.find_element(By.ID, "lname").send_keys("radha")
        self.driver.find_element(By.ID, "female").click()
        self.driver.find_element(By.ID, "option").click()
        dropdown = self.driver.find_element(By.ID, "option")
        dropdown.find_element(By.XPATH, "//option[. = 'Option 3']").click()
        dropdown = self.driver.find_element(By.ID, "owc")
        dropdown.find_element(By.XPATH, "//option[. = 'Option 3']").click()
        self.driver.find_element(By.NAME, "option3").click()
        self.driver.find_element(By.NAME, "Options").click()
        self.driver.find_element(By.NAME, "Options").send_keys("Strawberry")
        self.driver.find_element(By.ID, "favcolor").click()
        self.driver.find_element(By.ID, "favcolor").send_keys("#ff1a47")
        self.driver.find_element(By.CSS_SELECTOR, "fieldset:nth-child(1)").click()
        self.driver.find_element(By.ID, "day").click()
        self.driver.find_element(By.ID, "day").send_keys("2024-08-19")
        self.driver.find_element(By.ID, "a").send_keys("100")
        self.driver.find_element(By.ID, "a").click()
        self.driver.find_element(By.ID, "quantity").click()
        self.driver.find_element(By.ID, "quantity").send_keys("7")
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".btn")
        assert len(elements) > 0
        self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()
        assert self.driver.switch_to.alert.text == "Press a button!"
        self.driver.switch_to.alert.accept()
        self.driver.find_element(By.ID, "uname").click()
        self.driver.find_element(By.ID, "uname").send_keys("test")
        self.driver.find_element(By.ID, "pwd").send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()
        elements = self.driver.find_elements(By.LINK_TEXT, "here")
        assert len(elements) > 0

